// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdauagwejlbeskhcpxwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkYXVhZ3dlamxiZXNraGNweHdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MTg1NDQsImV4cCI6MjA2ODA5NDU0NH0.xI_2FaUsbZqwgeHekn9FWPw0Zr5YICL3Dff2tOM9nOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});